---                                                                                                                                                                              
# Home Assistant Core Configuation                                                                                                                                               
                                                                                                                                                                                 
http:                                                                                                                                                                            
  server_host: 0.0.0.0                                                                                                                                                           
  ip_ban_enabled: true                                                                                                                                                           
  login_attempts_threshold: 5                                                                                                                                                    
  use_x_forwarded_for: true                                                                                                                                                      
  trusted_proxies:                                                                                                                                                               
    # Pod CIDR                                                                                                                                                                   
    - 10.42.0.0/16                                                                                                                                                               
    # Node CIDR                                                                                                                                                                  
    - 192.168.30.0/24                                                                                                                                                            
    - 192.168.10.0/24                                                                                                                                                            
    - 192.168.20.0/24                                                                                                                                                            
                                                                                                                                                                                 
recorder:                                                                                                                                                                        
  db_url: !env_var postgresql_uri                                                                                                                                                
                                                                                                                                                                                 
shell_command:                                                                                                                                                                   
  update_config: cd /config && git pull                                                                                                                                          
                                                                                                                                                                                 
logger:                                                                                                                                                                          
  default: warn
  # logs:                                                                                                                                                                         
  #  homeassistant.components.homekit_controller: debug                                                                                                                          
  #  aiohomekit: debug

automation:
  # Update Configuration on Github Push Event
  - id: update_config_github_push_event
    alias: Update Configuration on Github Push Event

    trigger:
      - platform: webhook
        webhook_id: update_config

    action:
      - service: shell_command.update_config
      - service: homeassistant.restart

  - id: notify_on_homeassistant_start
    alias: Notification when Home Assistant starts
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: notify.home_assistant_discord
        data:
          target: !env_var discord_chat_id
          message: ""
          data:
            embed:
              title: "Home Assistant Started"
              color: 3840030
              url: !env_var self_uri
              fields:
                - name: version
                  value: '{{ states("sensor.current_version") }}'

  - id: notify_on_homeassistant_shutdown
    alias: Notification when Home Assistant Shutdown
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      - service: notify.home_assistant_discord
        data:
          target: !env_var discord_chat_id
          message: ""
          data:
            embed:
              title: "Home Assistant Shutdown"
              color: 11013171
              url: !env_var self_uri
              fields:
                - name: version
                  value: '{{ states("sensor.current_version") }}'
input_boolean:
  welcome_toggle:
    name: Toggle for UI Welcome card

influxdb:
  api_version: 2
  host: !env_var influxdb_host
  token: !env_var influxdb_token
  organization: !env_var influxdb_organization
  bucket: homeassistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units

  exclude:
    entity_globs:
      - sensor.browser*

  include:
    domains:
      - sun
      - climate
      - sensor
      - binary_sensor
    entities:
      - weather.maison
