---

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named configurations

frontend:
  themes: !include_dir_merge_named themes

browser_mod:
  prefix: "browser_"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
