---

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named configurations
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/16
      trusted_users:
        - 27f7fcd2f4db49b5b8c07f7bad6f6414
      allow_bypass_login: true
    - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes

browser_mod:
  prefix: "browser_"

lovelace:
  mode: storage
  dashboards:
    lovelace-tablet:
      mode: yaml
      title: iPad
      icon: mdi:tablet
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/tablet.yaml
    lovelace-tablet-test:
      mode: yaml
      title: iPad (Test)
      icon: mdi:tablet
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/tablet_test.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
