---

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named configurations

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
