---
# Heating System
# All about our heating
# Group of heating
group:
  heating_florian_bedroom:
    name: "Chauffage Chambre Florian"
    entities:
      - switch.heating_florian_bedroom_1
      - switch.heating_florian_bedroom_2
    icon: mdi:radiator
  heating_stairs:
    name: Chauffage Escalier
    icon: mdi:radiator
    entities:
      - switch.heating_stairs_cellar
      - switch.heating_stairs_groundfloor
      - switch.heating_stairs_firstfloor
  heating_kitchen:
    name: Chauffage Cuisine
    icon: mdi:radiator
    entities:
      - switch.heating_kitchen_roof
      - switch.heating_kitchen_wall

# Generic thermostat
climate:
  - platform: generic_thermostat
    name: Salon
    unique_id: 83f2b8bb-4c8b-4e0b-b429-1dab46d70829
    heater: switch.heating_livingroom
    target_sensor: sensor.temperature_salon
    # comfort_temp: input_number.heating_livingroom_mode_confort
    # home_temp: input_number.heating_livingroom_mode_eco
    <<: &climate_commun
      min_temp: 16
      max_temp: 23
      ac_mode: false
      away_temp: 18
      sleep_temp: 19
      home_temp: 20
  
  - platform: generic_thermostat
    name: Cuisine
    unique_id: c0839442-d1e3-4784-bbec-4a2da4c4d4ba
    heater: group.heating_kitchen
    target_sensor: sensor.temperature_cuisine
    # comfort_temp: input_number.heating_kitchen_mode_confort
    # home_temp: input_number.heating_kitchen_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Bureau Melanie
    unique_id: c319e4b0-05da-4acc-bc21-6cd05310de18
    heater: switch.heating_office_melanie
    target_sensor: sensor.temperature_bureau_melanie
    # comfort_temp: input_number.heating_office_melanie_mode_confort
    # home_temp: input_number.heating_office_melanie_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Bureau Clément
    unique_id: 8ba00103-6184-4fb7-97d2-3f08766af04f
    heater: switch.heating_office_clement
    target_sensor: sensor.temperature_bureau_clement
    # comfort_temp: input_number.heating_bedroom_cellar_mode_confort
    # home_temp: input_number.heating_bedroom_cellar_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Escalier
    unique_id: c635b55f-8730-4edc-bed8-ab8fd939094b
    heater: group.heating_stairs
    target_sensor: sensor.temperature_escalier
    # comfort_temp: input_number.heating_stairs_mode_confort
    # home_temp: input_number.heating_stairs_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Chambre Florian
    unique_id: 9c4ba8e3-406e-4a87-9867-7911e8cd5603
    heater: group.heating_florian_bedroom
    target_sensor: sensor.temperature_chambre_florian
    # comfort_temp: input_number.heating_florian_bedroom_mode_confort
    # home_temp: input_number.heating_florian_bedroom_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Chambre filles
    unique_id: dc873819-1c23-45f6-9aa3-dade9f77792c
    heater: switch.heating_girls_bedroom
    target_sensor: sensor.temperature_chambre_filles
    # comfort_temp: input_number.heating_bedroom_girls_mode_confort
    # home_temp: input_number.heating_bedroom_girls_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Chambre toit
    unique_id: 22678041-13fd-40e9-a703-931227ac4281
    heater: switch.heating_bedroom_roof
    target_sensor: sensor.temperature_chambre_toit
    # comfort_temp: input_number.heating_bedroom_roof_mode_confort
    # home_temp: input_number.heating_bedroom_roof_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Mezzanine
    unique_id: 1f87576d-8e6b-4b46-a486-58ff50d03c27
    heater: switch.heating_mezzanine
    target_sensor: sensor.temperature_mezzanine
    # comfort_temp: input_number.heating_mezzanine_mode_confort
    # home_temp: input_number.heating_mezzanine_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Laverie
    unique_id: a4760fff-c3a7-420d-8ac8-9c39a4ddd434
    heater: switch.heating_laundryroom
    target_sensor: sensor.temperature_laverie
    # comfort_temp: input_number.heating_laundryroom_mode_confort
    # home_temp: input_number.heating_laundryroom_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Salle de bain
    unique_id: 6a4c1198-efe2-423c-b9af-a3e3e41a8985
    heater: switch.heating_bathroom
    target_sensor: sensor.temperature_salle_de_bain
    # comfort_temp: input_number.heating_bathroom_mode_confort
    # home_temp: input_number.heating_bathroom_mode_eco
    <<: *climate_commun

  - platform: generic_thermostat
    name: Entrée
    unique_id: d311f9d2-914b-41fd-8222-832abbed865c
    heater: switch.heating_entrance
    target_sensor: sensor.temperature_entree
    # comfort_temp: input_number.heating_entrance_mode_confort
    # home_temp: input_number.heating_entrance_mode_eco
    <<: *climate_commun

# All targets
input_number:
  heating_laundryroom_mode_confort:
    name: Température Confort Buanderie
    <<: &temperature_high_common_options
      min: 0
      max: 25
      step: 0.5
      mode: box
      unit_of_measurement: °C
      icon: mdi:thermometer-high
  heating_bedroom_girls_mode_confort:
    name: Température Confort Chambre Filles
    <<: *temperature_high_common_options
  heating_bedroom_cellar_mode_confort:
    name: Température Confort Chambre Cave
    <<: *temperature_high_common_options
  heating_florian_bedroom_mode_confort:
    name: Température Confort Chambre Florian
    <<: *temperature_high_common_options
  heating_office_melanie_mode_confort:
    name: Température Confort Chambre RDC
    <<: *temperature_high_common_options
  heating_bedroom_roof_mode_confort:
    name: Température Confort Chambre Toit
    <<: *temperature_high_common_options
  heating_kitchen_mode_confort:
    name: Température Confort Cuisine
    <<: *temperature_high_common_options
  heating_entrance_mode_confort:
    name: Température Confort Entrée
    <<: *temperature_high_common_options
  heating_stairs_mode_confort:
    name: Température Confort Escalier
    <<: *temperature_high_common_options
  heating_mezzanine_mode_confort:
    name: Température Confort Mezzanine
    <<: *temperature_high_common_options
  heating_bathroom_mode_confort:
    name: Température Confort Salle de Bain
    <<: *temperature_high_common_options
  heating_livingroom_mode_confort:
    name: Température Confort Salon
    <<: *temperature_high_common_options

  heating_laundryroom_mode_eco:
    name: Température Reduite Buanderie
    <<: &temperature_low_common_options
      min: 0
      max: 25
      step: 0.5
      mode: box
      unit_of_measurement: °C
      icon: mdi:thermometer-low
  heating_bedroom_girls_mode_eco:
    name: Température Reduite Chambre Filles
    <<: *temperature_low_common_options
  heating_bedroom_cellar_mode_eco:
    name: Température Reduite Chambre Cave
    <<: *temperature_low_common_options
  heating_florian_bedroom_mode_eco:
    name: Température Reduite Chambre Florian
    <<: *temperature_low_common_options
  heating_office_melanie_mode_eco:
    name: Température Reduite Chambre RDC
    <<: *temperature_low_common_options
  heating_bedroom_roof_mode_eco:
    name: Température Reduite Chambre Toit
    <<: *temperature_low_common_options
  heating_kitchen_mode_eco:
    name: Température Reduite Cuisine
    <<: *temperature_low_common_options
  heating_entrance_mode_eco:
    name: Température Reduite Entrée
    <<: *temperature_low_common_options
  heating_stairs_mode_eco:
    name: Température Reduite Escalier
    <<: *temperature_low_common_options
  heating_mezzanine_mode_eco:
    name: Température Reduite Mezzanine
    <<: *temperature_low_common_options
  heating_bathroom_mode_eco:
    name: Température Reduite Salle de Bain
    <<: *temperature_low_common_options
  heating_livingroom_mode_eco:
    name: Température Reduite Salon
    <<: *temperature_low_common_options


# Heating mode
input_select:
  heating_mode:
    name: Mode Chauffage
    icon: mdi:radiator
    options:
      - Normal
      - Malade
      - Home Office
      - En vacance
      - Été

  heating_laundryroom_mode:
    name: Mode Chauffage Buanderie
    <<: &common_heating_mode
      icon: mdi:home-thermometer
      options:
        - Confort
        - Eco

  heating_bedroom_girls_mode:
    name: Mode Chauffage Chambre Filles
    <<: *common_heating_mode

  heating_bedroom_cellar_mode:
    name: Mode Chauffage Chambre Cave
    <<: *common_heating_mode

  heating_florian_bedroom_mode:
    name: Mode Chauffage Chambre Florian
    <<: *common_heating_mode

  heating_office_melanie_mode:
    name: Mode Chauffage Chambre RDC
    <<: *common_heating_mode

  heating_bedroom_roof_mode:
    name: Mode Chauffage Chambre Toit
    <<: *common_heating_mode

  heating_kitchen_mode:
    name: Mode Chauffage Cuisine
    <<: *common_heating_mode

  heating_entrance_mode:
    name: Mode Chauffage Entrée
    <<: *common_heating_mode

  heating_stairs_mode:
    name: Mode Chauffage Escalier
    <<: *common_heating_mode

  heating_mezzanine_mode:
    name: Mode Chauffage Mezzanine
    <<: *common_heating_mode

  heating_bathroom_mode:
    name: Mode Chauffage Salle de Bain
    <<: *common_heating_mode

  heating_livingroom_mode:
    name: Mode Chauffage Salon
    <<: *common_heating_mode


# Some extra sensors
sensor:
  - platform: history_stats
    name: Temps chauffage Salon Aujourd'hui
    entity_id: switch.heating_livingroom
    <<: &common_history_sensor
      state: 'on'
      type: time
      start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
      end: '{{ now() }}'
  - platform: history_stats
    name: Temps chauffage Cuisine Aujourd'hui
    entity_id: group.heating_kitchen
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Salle de bain Aujourd'hui
    entity_id: switch.heating_bathroom
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Chambre Cave Aujourd'hui
    entity_id: switch.heating_office_clement
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Chambre RDC Aujourd'hui
    entity_id: switch.heating_office_melanie
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Chambre 1er Aujourd'hui
    entity_id: switch.heating_girls_bedroom
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Chambre Florian Aujourd'hui
    entity_id: group.heating_florian_bedroom
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Chambre Toit Aujourd'hui
    entity_id: switch.heating_bedroom_roof
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Entrée Aujourd'hui
    entity_id: switch.heating_entrance
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Mezzanine Aujourd'hui
    entity_id: switch.heating_mezzanine
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Escalier Cave Aujourd'hui
    entity_id: switch.heating_stairs_cellar
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Escalier RDC Aujourd'hui
    entity_id: switch.heating_stairs_groundfloor
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Escalier 1er Aujourd'hui
    entity_id: switch.heating_stairs_firstfloor
    <<: *common_history_sensor
  - platform: history_stats
    name: Temps chauffage Buanderie Aujourd'hui
    entity_id: switch.heating_laundryroom
    <<: *common_history_sensor

  # Powercalc
  - platform: powercalc
    name: Consommation chauffage Salon Aujourd'hui
    entity_id: switch.heating_livingroom
    fixed:
      power:  2650
  - platform: powercalc
    name: Consommation chauffage Cuisine Aujourd'hui
    entity_id: group.heating_kitchen
    fixed:
      power:  1300
  - platform: powercalc
    name: Consommation chauffage Salle de bain Aujourd'hui
    entity_id: switch.heating_bathroom
    fixed:
      power: 850
  - platform: powercalc
    name: Consommation chauffage Chambre Cave Aujourd'hui
    entity_id: switch.heating_office_clement
    fixed:
      power: 1000
  - platform: powercalc
    name: Consommation chauffage Chambre RDC Aujourd'hui
    entity_id: switch.heating_office_melanie
    fixed:
      power: 1000
  - platform: powercalc
    name: Consommation chauffage Chambre 1er Aujourd'hui
    entity_id: switch.heating_girls_bedroom
    fixed:
      power: 1000
  - platform: powercalc
    name: Consommation chauffage Chambre Florian Aujourd'hui
    entity_id: group.heating_florian_bedroom
    fixed:
      power: 1700
  - platform: powercalc
    name: Consommation chauffage Chambre Toit Aujourd'hui
    entity_id: switch.heating_bedroom_roof
    fixed:
      power: 400
  - platform: powercalc
    name: Consommation chauffage Entrée Aujourd'hui
    entity_id: switch.heating_entrance
    fixed:
      power: 400
  - platform: powercalc
    name: Consommation chauffage Mezzanine Aujourd'hui
    entity_id: switch.heating_mezzanine
    fixed:
      power: 850
  - platform: powercalc
    name: Consommation chauffage Escalier Cave Aujourd'hui
    entity_id: switch.heating_stairs_cellar
    fixed:
      power: 1000
  - platform: powercalc
    name: Consommation chauffage Escalier RDC Aujourd'hui
    entity_id: switch.heating_stairs_groundfloor
    fixed:
      power: 850
  - platform: powercalc
    name: Consommation chauffage Escalier 1er Aujourd'hui
    entity_id: switch.heating_stairs_firstfloor
    fixed:
      power: 850
  - platform: powercalc
    name: Consommation chauffage Buanderie Aujourd'hui
    entity_id: switch.heating_laundryroom
    fixed:
      power: 650
