# All about lights On/Off - Groups
light:
  - platform: switch
    name: Ceiling Livingroom
    entity_id: switch.sonoff_touch_relay
  - platform: switch
    name: Plan Kitchen
    entity_id: switch.plug_kitchen_plan
  - platform: switch
    name: outside
    entity_id: switch.sonoff_basic_relay
  - platform: group
    name: stairs_first_floor
    entities:
      - light.yeelight_color_0x531b62d
      - light.stairs
  - platform: group
    name: kitchen_all
    entities:
      - light.kitchen_table
      - light.plan_kitchen
      - light.kitchen

  - platform: group
    name: kids_rooms
    entities:
      - light.florian_bedroom
      - light.bedroom_mina_clara

  - platform: group
    name: livingroom
    entities:
      - light.living_room_sofa
      - light.ceiling_livingroom
      - light.livingroom_sofa_side

  - platform: group
    name: Rez de chaussée
    entities:
      - light.livingroom
      - light.kitchen
      - light.bedroom_ground_floor
  
  - platform: group
    name: Tous
    entities:
      - light.rez_de_chaussee
      - light.kids_rooms
      - light.cellar_bedroom
# Automation on motion
automation:
  - id: 'dc710f9c-052f-4ef4-a204-8e2930cf57b4'
    alias: Lights >> First Floor on motion
    description: Handle lights when motion first floor stairs
    use_blueprint:
      path: clempat/motion_profile_light.yaml
      input:
        motion_entity: binary_sensor.motion_stairs_first_floor
        light_target:
          entity_id: light.stairs_first_floor

  - id: 'ecff519b-3881-4e27-8490-8d58e0e23461'
    alias: Lights >> Ground Floor on motion
    description: Handle lights when motion ground floor stairs
    use_blueprint:
      path: clempat/motion_profile_light.yaml
      input:
        motion_entity: binary_sensor.motion_stairs_ground_floor
        light_target:
          entity_id: light.yeelight_ceiling_stairs

  - id: '6c1414bf-2fab-4999-a531-14f3479c93b1'
    alias: Lights >> Cellar Stairs on motion
    description: Handle lights when motion cellar stairs
    use_blueprint:
      path: clempat/motion_profile_light.yaml
      input:
        motion_entity: binary_sensor.motion_stairs_cellar
        light_target:
          entity_id: light.hue_stairs_cellar

  - id: '1fb1b244-774c-4c9a-9a2b-178d3adb177b'
    alias: Lights >> Entrance on motion
    description: Handle lights when motion entrance
    use_blueprint:
      path: clempat/motion_profile_light.yaml
      input:
        motion_entity: binary_sensor.motion_entrance
        light_target:
          entity_id: light.ikea_entrance


  - id: '9d853aff-4679-4c0c-af2f-fff3318f6f2f'
    alias: Lights >> Outside
    description: Handle lights when motion outside
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        motion_entity: binary_sensor.motion_outside
        light_target:
          entity_id: light.outside

  - id: 'f322994d-cf02-48ed-852d-602f20cc4e6a'
    alias: Lights >> Mezzanine
    description: Handle lights when motion mezzanine
    use_blueprint:
      path: clempat/motion_profile_light.yaml
      input:
        motion_entity: binary_sensor.x_motion_stairs_mezzanine
        light_target:
          entity_id: light.mezzanine_floor

# Automation Buttons
  - id: b06ed59c-58f6-42dd-be49-c9346bc0c9f0
    alias: Lights >> Switch Kitchen 1
    description: ""
    use_blueprint:
      path: clempat/deconz-aqara-wireless-remote-switch-double-rocker-2-buttons.yaml
      input:
        remote: x_switch_kitchen_1
        button_left_single_press: 
          - service: light.toggle
            data: {}
            entity_id: light.yeelight_ceiling_kitchen
        button_left_long: []
        button_right_single_press:
          - service: light.toggle
            data: {}
            entity_id: light.kitchen_table
        both_button_single_press:
          - service: light.toggle
            data: {}
            entity_id: light.kitchen_all
  - id: 06f1b6a5-aa24-4127-b833-b38b64120624
    alias: Lights >> Switch Kitchen 2
    description: ""
    use_blueprint:
      path: clempat/deconz-aqara-wireless-remote-switch-double-rocker-2-buttons.yaml
      input:
        remote: x_switch_kitchen_2
        button_left_single_press: 
          - service: light.toggle
            entity_id: light.kitchen_ceiling
        button_left_long: []

  - description: Turn on kitchen plan when click on switch
    alias: Lights >> Turn on Kitchen Plan switch
    id: 447255e3-94fb-43ed-98fa-01a2b7669ac3

    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: x_switch_kitchen_plan
        event: 1002
    action:
      service: switch.toggle
      entity_id: switch.plug_kitchen_plan

  - id: a67d9b7c-5043-4bdb-b6d5-03e534c7a19f
    alias: Lights >> Melanie Office Switch
    description: ''
    use_blueprint:
      path: clempat/deconz-aqara-wireless-remote-switch-double-rocker-2-buttons.yaml
      input:
        remote: x_switch_double_melanie
        button_left_single_press:
        - service: light.toggle
          data: {}
          entity_id: light.bedroom_ground_floor
        
        button_right_single_press:
        - service: light.toggle
          data: {}
          entity_id: light.hue_melanie_office_sofa
          
  - id: d8f3dd82-0192-400c-bb57-236c00ce6e12
    alias: Lights >> Activate live scene round buuton

    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: x_round_button
        event: 1002

    action:
      - service: script.run_live
    mode: single
